# __Attributes and Functions in Python__

## __Agenda__
In this lesson, we will cover the following concepts with the help of examples:

- Attributes of NumPy Arrays
  * Explanation of Attributes
- NumPy Array Functions

## __1. Attributes of NumPy Arrays__ ##

Few common attributes of NumPy array:

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/2_Attributes_and_Functions_in_Python/Image_1.png)

In [ ]:
# An example for each attribute is given below:
import numpy as np
arr = np.array([[ 1, 2, 3], [ 4, 2, 5]])
print("No. of dimensions: ", arr.ndim)
print("Shape of array: ", arr.shape)
print("Size of array: ", arr.size)
print("Array stores elements of type: ", arr.dtype)
print("Length of one array element in bytes. : ", arr.itemsize)
print("array’s data. : ", arr.data)

No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int64
Length of one array element in bytes. :  8
array’s data. :  <memory at 0x7f3029ebacf0>


### __1.1 Explanation of Attributes:__ ###
- `ndarray.ndim`: It is the number of axes (dimensions) of the array.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/2_Attributes_and_Functions_in_Python/Image_2.png)

- `ndarray.shape`: It provides the size of the array for each dimension. The output data type is a tuple.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/2_Attributes_and_Functions_in_Python/Image_3.png)

- `ndarray.size` : It is the total number of elements in the array.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/2_Attributes_and_Functions_in_Python/Image_4.png)

- `ndarray.dtype`: It shows the data type of the elements in the array.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/2_Attributes_and_Functions_in_Python/Image_5.png)

- `ndarray.itemsize`: It shows the length of one array element in bytes.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/2_Attributes_and_Functions_in_Python/IMage_6.png)

- `ndarray.data`: It is an attribute offering direct access to the raw memory of a NumPy array.

## __2. NumPy Array Functions__ ##
![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/2_Attributes_and_Functions_in_Python/Image_7.png)

- `ndarray.reshape`: It is used to reshape (new shape) the current elements of an array.

In [ ]:
# Example: Converting a 1D Array to a 2D Array
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print (newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


- `ndarray.flatten`: It returns a copy of the array flattened into a 1D array.

In [ ]:
# Converting a multidimensional(3D) array into a 1D array
arr3D = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
flattened_array = arr3D.flatten()
flattened_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

- `ndarray.transpose`: It swaps the rows and columns of a 2D array.

In [ ]:
# Let's create a 2D array for the transpose example
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
# Transposing the 2D array
transposed_array = arr2D.transpose()
transposed_array

array([[1, 4],
       [2, 5],
       [3, 6]])

## __Assisted Practice__

### __Problem Statement:__

As a data scientist, your task is to create a Python project that explores NumPy arrays' attributes and functions. This project will deepen your understanding of NumPy arrays, including accessing their attributes and performing common operations using NumPy functions. Use the dataset containing daily temperature records for a week.

temperatures = [ 75.2, 77.1, 74.5, 79.3, 82.6, 81.2, 77.8 ]


**Steps to Perform:**

1. Explore the key attributes of NumPy arrays, including `ndim`, `shape`, `size`, `dtype`, `itemsize`, and `data`.
2. Demonstrate important NumPy array functions such as `reshape`, `flatten`, and `transpose`.